### ISSUE TITLE
Handling irregular spacing

### ISSUE THREAD

**Issue by luhugerth** [ctmrbio/Amplicon_workflows#2]
Guppy outputs an upper diagonal matrix spaced with irregular amounts of spaces. To be able to use the script in it's current form one has to open this file in a text editor, replace every set of multiple spaces for a single tab and then remove any tabs in the beginning of each line. How could we avoid this manual step??

A solution within the script is preferred, but even a smart bash one-liner to use before it will do.

**Comment by boulund** [comment]
What script are you referring to? 

Replacing irregular amounts of spaces and single tabs sounds like a job for `tr` and `sed` in bash. But I agree with you that it would probably be preferable to fix it within the script.

**Comment by luhugerth** [comment]
Yes, way to put the issue in the wrong flow, me XP

This one: https://github.com/ctmrbio/Amplicon_workflows/blob/master/make_dist_mat.py

**Comment by boulund** [comment]
Sounds like a fun Friday night problem. I might give it a go tonight if I feel inspired :). 

Could you provide me with an example input file and a description of the expected output?

**Comment by luhugerth** [comment]
Guppy produces raw_guppy_input.txt and R requires expected_R_input.txt (egentligen tsv, men git tillåter inte .tsv)

I don't know how to automatically process raw_guppy_input.txt, so I'm opening vim to convert that to expected_script_input.txt (also a tsv), which I then know how to parse.

By-passing that middle step would be great!


[expected_R_input.txt](https://github.com/ctmrbio/Amplicon_workflows/files/799423/expected_R_input.txt)
[expected_script_input.txt](https://github.com/ctmrbio/Amplicon_workflows/files/799424/expected_script_input.txt)
[raw_guppy_output.txt](https://github.com/ctmrbio/Amplicon_workflows/files/799419/raw_guppy_output.txt)

**Comment by boulund** [comment]
Ah, so we're going from a upper diagonal matrix in `raw_guppy_output.txt` that needs to be in a symmetric matrix format for `expected_R_input.tsv`? Should be easy enough! I'll report back with a solution when I have one.

**Comment by boulund** [comment]
Made a PR with a solution. I takes files like `raw_guppy_output.txt` and converts them to the format of `expected_R_input.tsv`. Prints to `stdout` per default, but has an option to write to a file instead. Shows help output if called without arguments. And a basic file format check is in place. No other error checking...
